NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.orgalibaba.bep.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.orgalibaba.bep.com-cert.pem
    OrganizationalUnitIdentifier: peer
