name: "bep-network"
version: 1.0.0
client:

  organization: Org1

  logging:
    level: info

  cryptoconfig:
    path: ${GOPATH}/src/github.com/BEP/fixtures/crypto-config

  credentialStore:
    path: /tmp/bep-store

    cryptoStore:
      path: /tmp/bep-msp

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256

  tlsCerts:
    systemCertPool: false

    client:
      key:
        path:
      cert:
        path:

channels:
  BEPChannel:
    peers:
      peer0.org1.bep.com:
        endorsingPeer: true

        chaincodeQuery: true

        ledgerQuery: true

        eventSource: true

      peer1.org1.bep.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 10
        peerMonitorPeriod: 5s

organizations:
  Org1:
    mspid: org1.bep.com
    cryptoPath: peerOrganizations/org1.bep.com/users/{userName}@org1.bep.com/msp
    peers:
      - peer0.org1.bep.com
      - peer1.org1.bep.com

    certificateAuthorities:
      - ca.org1.bep.com

orderers:
  orderer.bep.com:
    url: localhost:7050

    grpcOptions:
      ssl-target-name-override: orderer.bep.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ${GOPATH}/src/github.com/BEP/fixtures/crypto-config/ordererOrganizations/bep.com/tlsca/tlsca.bep.com-cert.pem

peers:
  peer0.org1.bep.com:
    url: localhost:7051
    eventUrl: localhost:7053

    grpcOptions:
      ssl-target-name-override: peer0.org1.bep.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ${GOPATH}/src/github.com/BEP/fixtures/crypto-config/peerOrganizations/org1.bep.com/tlsca/tlsca.org1.bep.com-cert.pem

  peer1.org1.bep.com:
    url: localhost:7151
    eventUrl: localhost:7153

    grpcOptions:
      ssl-target-name-override: peer1.org1.bep.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

    tlsCACerts:
      path: ${GOPATH}/src/github.com/BEP/fixtures/crypto-config/peerOrganizations/org1.bep.com/tlsca/tlsca.org1.bep.com-cert.pem

certificateAuthorities:
  ca.org1.bep.com:
    url: http://localhost:7054
    tlsCACerts:
      path: ${GOPATH}/src/github.com/BEP/fixtures/crypto-config/peerOrganizations/org1.bep.com/ca/ca.org1.bep.com-cert.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.bep.com

entityMatchers:
  peer:
    - pattern: (\w*)peer0.org1.bep.com(\w*)
      urlSubstitutionExp: localhost:7051
      eventUrlSubstitutionExp: localhost:7053
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.bep.com
      mappedHost: peer0.org1.bep.com

    - pattern: (\w*)peer1.org1.bep.com(\w*)
      urlSubstitutionExp: localhost:7151
      eventUrlSubstitutionExp: localhost:7153
      sslTargetOverrideUrlSubstitutionExp: peer1.org1.bep.com
      mappedHost: peer1.org1.bep.com

  orderer:
    - pattern: (\w*)orderer.bep.com(\w*)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.bep.com
      mappedHost: orderer.bep.com

  certificateAuthorities:
    - pattern: (\w*)ca.org1.bep.com(\w*)
      urlSubstitutionExp: http://localhost:7054
      mappedHost: ca.org1.bep.com
