ignored = ["github.com/BEP/chaincode"]

[[constraint]]
  # Release v1.0.0-alpha4
  name = "github.com/hyperledger/fabric-sdk-go"
  revision = "a906355f73d060d7bf95874a9e90dc17589edbb3"

[[constraint]]
  name = "github.com/satori/go.uuid"
  #version = "1.2.0"
  branch = "master"

[[override]]
  revision = "4e2dcbde500472449917533851bf4bae9bdff562"
  name = "github.com/cloudflare/cfssl"
