# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.BEP.com:
  peer0.OrgAlibaba.BEP.com:
  peer1.OrgAlibaba.BEP.com:
  peer0.OrgBaidu.BEP.com:
  peer1.OrgBaidu.BEP.com:

networks:
  BEP:

services:

  orderer.BEP.com:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.BEP.com
    container_name: orderer.BEP.com
    networks:
      - BEP

  peer0.OrgAlibaba.BEP.com:
    container_name: peer0.OrgAlibaba.BEP.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.OrgAlibaba.BEP.com
    networks:
      - BEP

  peer1.OrgAlibaba.BEP.com:
    container_name: peer1.OrgAlibaba.BEP.com
    extends:
      file:  docker-compose-base.yaml
      service: peer1.OrgAlibaba.BEP.com
    networks:
      - BEP

  peer0.OrgBaidu.BEP.com:
    container_name: peer0.OrgBaidu.BEP.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.OrgBaidu.BEP.com
    networks:
      - BEP

  peer1.OrgBaidu.BEP.com:
    container_name: peer1.OrgBaidu.BEP.com
    extends:
      file:  docker-compose-base.yaml
      service: peer1.OrgBaidu.BEP.com
    networks:
      - BEP

  ca.OrgAlibaba.BEP.com:
    container_name: ca.OrgAlibaba.BEP.com
    extends:
      service: ca.OrgAlibaba.BEP.com
      file: docker-compose-base.yaml
    networks:
      - BEP

  ca.OrgBaidu.BEP.com:
    container_name: ca.OrgBaidu.BEP.com
    extends:
      service: ca.OrgBaidu.BEP.com
      file: docker-compose-base.yaml
    networks:
      - BEP

  cli:
    container_name: cli
    image: hyperledger/fabric-tools #:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/home/lxs/Application/go
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO #日志级别,critical,error,warning,notice,info,debug从高到低
      - CORE_PEER_ID=cli #当前节点的ID即名字
      - CORE_PEER_ADDRESS=peer0.OrgAlibaba.BEP.com:7051 #连接peer节点的地址
      - CORE_PEER_LOCALMSPID=OrgAlibaba #连接peer节点所属的组织
      - CORE_PEER_TLS_ENABLED=true #是否使用TLS加密,true时下面的3个文件才生效
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/OrgAlibaba.BEP.com/peers/peer0.OrgAlibaba.BEP.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/OrgAlibaba.BEP.com/peers/peer0.OrgAlibaba.BEP.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/OrgAlibaba.BEP.com/peers/peer0.OrgAlibaba.BEP.com/tls/ca.crt #客户端角色,连接网络访问节点,需要账号
      # 普通账号: 交易(写数据),查询(读数据)
      # 管理员账号: 交易(写数据),查询(读数据),创建通道,让某个节点加入到通道,安装链码,链码初始化
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/OrgAlibaba.BEP.com/users/Admin@OrgAlibaba.BEP.com/msp
#    working_dir: /home/lxs/Application/go/src/github.com/hyperledger/fabric/peer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.BEP.com
      - peer0.OrgAlibaba.BEP.com
      - peer1.OrgAlibaba.BEP.com
      - peer0.OrgBaidu.BEP.com
      - peer1.OrgBaidu.BEP.com
      - ca.OrgAlibaba.BEP.com
      - ca.OrgBaidu.BEP.com
    networks:
      - BEP
