export const FETCH_STATUS = {
    FETCH_BEGIN: "FETCH_BEGIN",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_FAIL: "FECH_FAIL",
}

export const RequestActionTypes = {
    SHOW_ALL_REQUESTS: 'SHOW_ALL_REQUESTS',
    QUERY_REQUESTS_BY_USER_ID: 'QUERY_REQUESTS_BY_USER_ID',
    PUSH_REQUEST: 'PUSH_REQUEST',
}

export const ResponseActionTypes = {
    QUERY_RESPONSES_BY_USER_ID: 'QUERY_RESPONSES_BY_USER_ID',
    QUERY_RESPONSES_BY_REQUEST_ID: 'QUERY_RESPONSES_BY_REQUEST_ID',
    PUSH_RESPONSE: 'PUSH_RESPONSE',
}

export const UserActionTypes = {
    QUERY_USER_BALANCE_BY_USER_ID: 'QUERY_USER_BALANCE_BY_USER_ID',
    ACCPET_RESPONSE: 'ACCPET_RESPONSE',
}